#!/usr/bin/env python3
"""
scripts/gen-kernel-syscall-tbl.py — generate a permuted syscall_64.tbl
for the kernel build (Phase 2 M1+M3).

Inputs:
  - The canonical Linux x86_64 syscall table at
    scripts/upstream/syscall_64.tbl.
  - The master seed (env var ENCRYPTED_LINUX_SEED, or ./seed).

Output:
  - build/generated/kernel/syscall_64.tbl — same format as upstream,
    but every (number, name, entry) row has its number replaced with
    the seed-permuted index emitted by gen-unistd-seeded.py.

The renumbering algorithm is identical to gen-unistd-seeded.py (both
call into the shared functions in that module), so the kernel table
and the userspace unistd_seeded.h always agree.

Format is preserved verbatim, so it drops straight into
arch/x86/entry/syscalls/syscall_64.tbl. The kernel's existing
scripts/syscallhdr.sh + syscalltbl.sh + scripts/Makefile.asm-headers
machinery generates correct unistd_64.h (userspace) and dispatch
table (kernel side) from the permuted .tbl.

x32 rows (numbers 512+) are passed through unchanged.

License: Apache-2.0
"""
from __future__ import annotations
import argparse
import importlib.util
import os
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import seed_lib  # noqa: E402

# Import gen-unistd-seeded as a module (its filename has a hyphen).
_spec = importlib.util.spec_from_file_location(
    "gen_unistd_seeded", HERE / "gen-unistd-seeded.py"
)
gus = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(gus)


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--input",
                   default=str(HERE / "upstream" / "syscall_64.tbl"))
    p.add_argument("--output",
                   default=str(HERE.parent / "build" / "generated" / "kernel" /
                               "syscall_64.tbl"))
    p.add_argument("--seed",
                   help="64-hex master seed; default $ENCRYPTED_LINUX_SEED or ./seed")
    args = p.parse_args()

    # Resolve seed.
    if args.seed:
        seed_bytes = args.seed.strip().encode("ascii")
    elif "ENCRYPTED_LINUX_SEED" in os.environ:
        seed_bytes = os.environ["ENCRYPTED_LINUX_SEED"].strip().encode("ascii")
    else:
        seed_bytes = seed_lib.read_seed()

    if len(seed_bytes) != 64:
        sys.exit(f"seed must be 64 hex chars, got {len(seed_bytes)}")

    syscall_seed_hex = seed_lib.derive("syscall.numbers", seed=seed_bytes)
    # Match gen-unistd-seeded.py's convention: encode the hex string as
    # ASCII for the HMAC key, NOT the decoded raw bytes. This keeps the
    # kernel's syscall_64.tbl numbering identical to userspace's
    # unistd_seeded.h numbering.
    syscall_seed = syscall_seed_hex.encode("ascii")

    # Parse the upstream table.
    entries = gus.parse_syscall_tbl(Path(args.input))
    # gen-unistd-seeded.py renumbers only "common"/"64" entries.
    main_entries = [e for e in entries if e["abi"] in ("common", "64")]

    slot_map, stats = gus.renumber(main_entries, syscall_seed)
    canon_to_new = {e["name"]: e["new_number"] for e in slot_map.values()}

    # Re-read raw lines so we can preserve x32 + comments verbatim.
    raw_lines = Path(args.input).read_text().splitlines()

    out_lines = [
        "#",
        "# encrypted-linux: PERMUTED 64-bit syscall numbers",
        f"# Master seed (first 16 hex): {seed_bytes.decode()[:16]}...",
        f"# Permutation seed (first 16 hex): {syscall_seed_hex[:16]}...",
        f"# Renumbered entries: {len(canon_to_new)} (load factor: {stats['load_factor']})",
        f"# Linear-probe collisions: {stats['collisions']} (max probes: {stats['max_probes']})",
        "#",
        "# Generated by scripts/gen-kernel-syscall-tbl.py. DO NOT EDIT.",
        "#",
        "# Format: <number> <abi> <name> <entry point>",
        "#",
    ]

    # Two passes: first collect rows + numbers, then sort by number.
    # The kernel's syscalltbl.sh enforces "sorted by number, unique".
    rebuilt_rows: list[tuple[int, str]] = []
    for line in raw_lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        parts = line.split(maxsplit=3)
        if len(parts) < 3:
            continue
        try:
            orig_num = int(parts[0])
        except ValueError:
            continue
        abi = parts[1]
        name = parts[2]
        entry = parts[3].rstrip() if len(parts) > 3 else ""
        if abi in ("common", "64") and name in canon_to_new:
            new_num = canon_to_new[name]
            rebuilt_rows.append((new_num, f"{new_num}\t{abi}\t{name}\t{entry}".rstrip()))
        elif abi == "x32":
            # Drop x32 entirely — vestigial ABI, not part of the PoC, and
            # canonical x32 numbers (512-547) collide with our permuted
            # 1024-slot common-syscall numbers. CONFIG_X86_X32 is off
            # by default in tinyconfig, so dropping is safe.
            continue
        else:
            rebuilt_rows.append((orig_num, line.rstrip()))

    # Sort by number; the kernel build requires this.
    rebuilt_rows.sort(key=lambda x: x[0])
    seen = set()
    for n, _ in rebuilt_rows:
        if n in seen:
            sys.exit(f"ERROR: duplicate syscall number {n} after renumbering (bug in renumber())")
        seen.add(n)

    for _, row_text in rebuilt_rows:
        out_lines.append(row_text)

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(out_lines) + "\n")
    print(f"wrote {out} ({len(canon_to_new)} renumbered, "
          f"{stats['collisions']} collisions resolved)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
