#!/usr/bin/env python3
"""
scripts/gen-errno-permutation.py — generate a per-build permutation of
POSIX errno values (Idea #6 from research/08).

POSIX guarantees errno NAMES (EAGAIN, ENOENT, ...) are constants but
explicitly does NOT pin their integer values. Linux pins 1-133 to
SUSv4 conventions for 30 years; nothing requires this. We permute.

Outputs:
  build/generated/errno_map.json  — { name -> new_number }
  build/generated/asm-generic/errno-base.h  — kernel-side (UAPI)
  build/generated/asm-generic/errno.h       — kernel-side (UAPI)
  build/generated/musl-errno.h              — musl bits/errno.h

The kernel and musl MUST use the same permutation; both pick it up
from build/generated/.

License: Apache-2.0
"""
from __future__ import annotations
import hashlib
import hmac
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import seed_lib  # noqa: E402

OUT_DIR = HERE.parent / "build" / "generated"

# Canonical Linux x86_64 errno values 1..133. Sourced from
# include/uapi/asm-generic/errno-base.h (1-34) and
# include/uapi/asm-generic/errno.h (35-133).
CANONICAL_ERRNO = {
    "EPERM": 1, "ENOENT": 2, "ESRCH": 3, "EINTR": 4, "EIO": 5,
    "ENXIO": 6, "E2BIG": 7, "ENOEXEC": 8, "EBADF": 9, "ECHILD": 10,
    "EAGAIN": 11, "ENOMEM": 12, "EACCES": 13, "EFAULT": 14, "ENOTBLK": 15,
    "EBUSY": 16, "EEXIST": 17, "EXDEV": 18, "ENODEV": 19, "ENOTDIR": 20,
    "EISDIR": 21, "EINVAL": 22, "ENFILE": 23, "EMFILE": 24, "ENOTTY": 25,
    "ETXTBSY": 26, "EFBIG": 27, "ENOSPC": 28, "ESPIPE": 29, "EROFS": 30,
    "EMLINK": 31, "EPIPE": 32, "EDOM": 33, "ERANGE": 34,
    "EDEADLK": 35, "ENAMETOOLONG": 36, "ENOLCK": 37, "ENOSYS": 38,
    "ENOTEMPTY": 39, "ELOOP": 40, "EWOULDBLOCK": 11,  # alias of EAGAIN
    "ENOMSG": 42, "EIDRM": 43, "ECHRNG": 44, "EL2NSYNC": 45,
    "EL3HLT": 46, "EL3RST": 47, "ELNRNG": 48, "EUNATCH": 49, "ENOCSI": 50,
    "EL2HLT": 51, "EBADE": 52, "EBADR": 53, "EXFULL": 54, "ENOANO": 55,
    "EBADRQC": 56, "EBADSLT": 57, "EDEADLOCK": 35,  # alias of EDEADLK
    "EBFONT": 59, "ENOSTR": 60, "ENODATA": 61, "ETIME": 62, "ENOSR": 63,
    "ENONET": 64, "ENOPKG": 65, "EREMOTE": 66, "ENOLINK": 67, "EADV": 68,
    "ESRMNT": 69, "ECOMM": 70, "EPROTO": 71, "EMULTIHOP": 72, "EDOTDOT": 73,
    "EBADMSG": 74, "EOVERFLOW": 75, "ENOTUNIQ": 76, "EBADFD": 77,
    "EREMCHG": 78, "ELIBACC": 79, "ELIBBAD": 80, "ELIBSCN": 81,
    "ELIBMAX": 82, "ELIBEXEC": 83, "EILSEQ": 84, "ERESTART": 85,
    "ESTRPIPE": 86, "EUSERS": 87, "ENOTSOCK": 88, "EDESTADDRREQ": 89,
    "EMSGSIZE": 90, "EPROTOTYPE": 91, "ENOPROTOOPT": 92,
    "EPROTONOSUPPORT": 93, "ESOCKTNOSUPPORT": 94, "EOPNOTSUPP": 95,
    "EPFNOSUPPORT": 96, "EAFNOSUPPORT": 97, "EADDRINUSE": 98,
    "EADDRNOTAVAIL": 99, "ENETDOWN": 100, "ENETUNREACH": 101,
    "ENETRESET": 102, "ECONNABORTED": 103, "ECONNRESET": 104,
    "ENOBUFS": 105, "EISCONN": 106, "ENOTCONN": 107, "ESHUTDOWN": 108,
    "ETOOMANYREFS": 109, "ETIMEDOUT": 110, "ECONNREFUSED": 111,
    "EHOSTDOWN": 112, "EHOSTUNREACH": 113, "EALREADY": 114, "EINPROGRESS": 115,
    "ESTALE": 116, "EUCLEAN": 117, "ENOTNAM": 118, "ENAVAIL": 119,
    "EISNAM": 120, "EREMOTEIO": 121, "EDQUOT": 122, "ENOMEDIUM": 123,
    "EMEDIUMTYPE": 124, "ECANCELED": 125, "ENOKEY": 126, "EKEYEXPIRED": 127,
    "EKEYREVOKED": 128, "EKEYREJECTED": 129, "EOWNERDEAD": 130,
    "ENOTRECOVERABLE": 131, "ERFKILL": 132, "EHWPOISON": 133,
}


def derive_errno_seed(master_seed: bytes) -> bytes:
    """HMAC-SHA256(master, "kernel.errno") — fresh label for errno
    permutation, independent of other seed labels."""
    return hmac.new(master_seed, b"kernel.errno", hashlib.sha256).digest()


def permute(canonical: dict[str, int], seed: bytes) -> dict[str, int]:
    """Permute the [1..133] range deterministically from the seed.

    Aliases (EWOULDBLOCK=EAGAIN, EDEADLOCK=EDEADLK) preserve their
    target's new value.
    """
    # Build the set of distinct canonical values that need permuting.
    distinct_vals = sorted({v for v in canonical.values()})

    # Fisher-Yates shuffle keyed by the seed.
    perm = list(distinct_vals)
    state = int.from_bytes(seed, "big")
    for i in range(len(perm) - 1, 0, -1):
        j = state % (i + 1)
        perm[i], perm[j] = perm[j], perm[i]
        state = int.from_bytes(
            hashlib.sha256(state.to_bytes(32, "big") + b"errno").digest(),
            "big",
        )

    old_to_new = dict(zip(distinct_vals, perm))

    return {name: old_to_new[v] for name, v in canonical.items()}


def emit_kernel_base_header(perm: dict[str, int]) -> str:
    """Render the kernel's UAPI asm-generic/errno-base.h (errnos 1-34)."""
    lines = [
        "/* errno-base.h -- per-build permuted POSIX errno values.",
        " *",
        " * GENERATED by scripts/gen-errno-permutation.py.",
        " * POSIX guarantees names, not integer values.",
        " */",
        "",
        "#ifndef _ASM_GENERIC_ERRNO_BASE_H",
        "#define _ASM_GENERIC_ERRNO_BASE_H",
        "",
    ]
    # errno-base.h covers EPERM..ERANGE (canonical 1-34) plus EAGAIN/EDEADLK
    # aliases.
    base_names = ["EPERM", "ENOENT", "ESRCH", "EINTR", "EIO", "ENXIO",
                  "E2BIG", "ENOEXEC", "EBADF", "ECHILD", "EAGAIN",
                  "ENOMEM", "EACCES", "EFAULT", "ENOTBLK", "EBUSY",
                  "EEXIST", "EXDEV", "ENODEV", "ENOTDIR", "EISDIR",
                  "EINVAL", "ENFILE", "EMFILE", "ENOTTY", "ETXTBSY",
                  "EFBIG", "ENOSPC", "ESPIPE", "EROFS", "EMLINK",
                  "EPIPE", "EDOM", "ERANGE"]
    for name in base_names:
        lines.append(f"#define {name:<10} {perm[name]:3d}")
    lines.append("")
    lines.append("#endif")
    lines.append("")
    return "\n".join(lines)


def emit_kernel_full_header(perm: dict[str, int]) -> str:
    """Render the kernel's UAPI asm-generic/errno.h (errnos 35-133)."""
    lines = [
        "/* errno.h -- per-build permuted POSIX errno values.",
        " *",
        " * GENERATED by scripts/gen-errno-permutation.py.",
        " * POSIX guarantees names, not integer values.",
        " */",
        "",
        "#ifndef _ASM_GENERIC_ERRNO_H",
        "#define _ASM_GENERIC_ERRNO_H",
        "",
        "#include <asm-generic/errno-base.h>",
        "",
    ]
    base_set = {"EPERM", "ENOENT", "ESRCH", "EINTR", "EIO", "ENXIO",
                "E2BIG", "ENOEXEC", "EBADF", "ECHILD", "EAGAIN",
                "ENOMEM", "EACCES", "EFAULT", "ENOTBLK", "EBUSY",
                "EEXIST", "EXDEV", "ENODEV", "ENOTDIR", "EISDIR",
                "EINVAL", "ENFILE", "EMFILE", "ENOTTY", "ETXTBSY",
                "EFBIG", "ENOSPC", "ESPIPE", "EROFS", "EMLINK",
                "EPIPE", "EDOM", "ERANGE"}
    # Emit in canonical-name-sorted order for stable diffs.
    for name in sorted(perm.keys()):
        if name in base_set:
            continue
        lines.append(f"#define {name:<18} {perm[name]:3d}")
    lines.append("")
    lines.append("#define EWOULDBLOCK\tEAGAIN")
    lines.append("#define EDEADLOCK\tEDEADLK")
    lines.append("")
    lines.append("#endif")
    lines.append("")
    return "\n".join(lines)


def emit_musl_header(perm: dict[str, int]) -> str:
    """Render musl's arch/generic/bits/errno.h equivalent.

    musl's bits/errno.h is short — just #define E* numbers. We
    provide a drop-in replacement.
    """
    lines = [
        "/* errno values -- per-build permuted via encrypted-linux.",
        " * GENERATED by scripts/gen-errno-permutation.py. */",
        "",
    ]
    for name in sorted(perm.keys()):
        if name in ("EWOULDBLOCK", "EDEADLOCK"):
            continue
        lines.append(f"#define {name:<18} {perm[name]:3d}")
    lines.append("")
    lines.append("#define EWOULDBLOCK\tEAGAIN")
    lines.append("#define EDEADLOCK\tEDEADLK")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    seed = seed_lib.read_seed()
    errno_seed = derive_errno_seed(seed)
    perm = permute(CANONICAL_ERRNO, errno_seed)

    (OUT_DIR / "asm-generic").mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "asm-generic" / "errno-base.h").write_text(
        emit_kernel_base_header(perm))
    (OUT_DIR / "asm-generic" / "errno.h").write_text(
        emit_kernel_full_header(perm))
    (OUT_DIR / "musl-errno.h").write_text(emit_musl_header(perm))
    (OUT_DIR / "errno_map.json").write_text(
        json.dumps(perm, indent=2, sort_keys=True) + "\n")

    print(f"errno permutation seed: {errno_seed.hex()[:16]}...")
    print("Sample permutation:")
    for name in ("EPERM", "ENOENT", "EAGAIN", "EINVAL", "ENOSYS", "ENOMEM"):
        print(f"  {name:<10} canonical={CANONICAL_ERRNO[name]:3d}  "
              f"new={perm[name]:3d}")
    print(f"Wrote {OUT_DIR}/asm-generic/errno{{,-base}}.h, musl-errno.h, "
          f"errno_map.json")
    return 0


if __name__ == "__main__":
    sys.exit(main())
