#!/usr/bin/env python3
"""
scripts/gen-gcc-arg-perm.py — generate the x86_64 argument-register
permutation header consumed by patches/scramble-gcc-v0.patch.

Output: gcc/config/i386/encrypted-linux-perm.h, containing the
declaration of `x86_64_int_parameter_registers[6]` that the patched
GCC's i386.cc #includes instead of its inline default.

Algorithm:
    USER_ABI_SEED = HMAC-SHA256(master_seed, "user.abi")
    ARG_REG_SEED  = HMAC-SHA256(USER_ABI_SEED, "x86_64.arg_regs")
    permutation   = Fisher-Yates shuffle of [0..5] keyed by ARG_REG_SEED

Behavior:
    - With $ENCRYPTED_LINUX_SEED set (64 hex chars): emit the permuted
      header. GCC built against this header will permute integer
      argument-register assignment deterministically per seed.
    - Without $ENCRYPTED_LINUX_SEED set: emit the canonical SysV header.
      GCC built against this header is bit-for-bit identical to stock
      upstream GCC. This lets the patch always apply cleanly.

The salt strings ("user.abi", "x86_64.arg_regs") are frozen and must
match scripts/seed_lib.py and scripts/seed-lib.sh. Changing them
breaks every downstream build.

License: Apache-2.0
"""
from __future__ import annotations
import argparse
import hashlib
import hmac
import os
import sys
from pathlib import Path

# GCC's SysV integer arg registers, in canonical order.
# These names must match the C preprocessor macros in gcc/config/i386/i386.h.
SYSV_ARG_REGS = ["DI_REG", "SI_REG", "DX_REG", "CX_REG", "R8_REG", "R9_REG"]

SALT_USER_ABI = b"user.abi"
SALT_ARG_REGS = b"x86_64.arg_regs"


def hmac_sha256(key: bytes, msg: bytes) -> bytes:
    return hmac.new(key, msg, hashlib.sha256).digest()


def derive_arg_reg_seed(master_seed_hex: str) -> bytes:
    master = bytes.fromhex(master_seed_hex.strip())
    if len(master) != 32:
        raise ValueError(f"master seed must be 32 bytes (got {len(master)})")
    user_abi = hmac_sha256(master, SALT_USER_ABI)
    return hmac_sha256(user_abi, SALT_ARG_REGS)


def fisher_yates(n: int, seed_bytes: bytes) -> list[int]:
    """Deterministic Fisher-Yates shuffle of [0..n-1] using seed_bytes
    as a random source. Consumes log2(n!) bits ≈ 9.5 bits for n=6,
    so 32 bits of seed are plenty.

    We treat seed_bytes as a big-endian integer and use it to draw
    successive indices via modular reduction with rejection sampling
    (simple modulo gives near-uniform for small n).
    """
    if n <= 1:
        return list(range(n))

    # Use a 256-bit integer as our PRNG state. After each draw we
    # advance the state by hashing it. This gives a deterministic
    # stream of bits.
    state = int.from_bytes(seed_bytes, "big")
    perm = list(range(n))

    for i in range(n - 1, 0, -1):
        # Draw j uniformly in [0, i]. With i < 6, modulo bias is
        # negligible for the headline goal (per-build uniqueness, not
        # cryptographic uniformity — see plan/03 §1).
        j = state % (i + 1)
        perm[i], perm[j] = perm[j], perm[i]
        state = int.from_bytes(
            hashlib.sha256(state.to_bytes(32, "big")).digest(), "big"
        )

    return perm


def emit_header(perm: list[int], seed_hash: str, output: Path) -> None:
    """Write encrypted-linux-perm.h with the permuted register table."""
    permuted_regs = [SYSV_ARG_REGS[p] for p in perm]

    header = f"""\
/* encrypted-linux-perm.h
 *
 * Generated by scripts/gen-gcc-arg-perm.py. DO NOT EDIT BY HAND.
 *
 * Permuted x86_64 SysV integer argument-register table for the
 * encrypted-linux scrambling GCC. See patches/scramble-gcc-v0.patch
 * and plan/01 M1.
 *
 * Seed hash (first 16 hex of HMAC(master, "user.abi")):
 *   {seed_hash}
 *
 * Permutation (canonical -> emitted):
 *   arg0 ({SYSV_ARG_REGS[0]:8}) -> {permuted_regs[0]}
 *   arg1 ({SYSV_ARG_REGS[1]:8}) -> {permuted_regs[1]}
 *   arg2 ({SYSV_ARG_REGS[2]:8}) -> {permuted_regs[2]}
 *   arg3 ({SYSV_ARG_REGS[3]:8}) -> {permuted_regs[3]}
 *   arg4 ({SYSV_ARG_REGS[4]:8}) -> {permuted_regs[4]}
 *   arg5 ({SYSV_ARG_REGS[5]:8}) -> {permuted_regs[5]}
 */

#ifndef GCC_ENCRYPTED_LINUX_PERM_H
#define GCC_ENCRYPTED_LINUX_PERM_H

static int const x86_64_int_parameter_registers[6] =
{{
  {permuted_regs[0]}, {permuted_regs[1]}, {permuted_regs[2]},
  {permuted_regs[3]}, {permuted_regs[4]}, {permuted_regs[5]}
}};

#endif /* GCC_ENCRYPTED_LINUX_PERM_H */
"""
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(header)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate encrypted-linux-perm.h for the scrambling GCC."
    )
    parser.add_argument(
        "--seed",
        help="64-hex-char master seed. Default: $ENCRYPTED_LINUX_SEED or contents of ./seed.",
    )
    parser.add_argument(
        "-o", "--output",
        default="gcc/config/i386/encrypted-linux-perm.h",
        help="Output header path (default: %(default)s).",
    )
    parser.add_argument(
        "-v", "--verbose", action="store_true",
        help="Print the permutation to stderr.",
    )
    args = parser.parse_args()

    # Resolve seed.
    seed = args.seed or os.environ.get("ENCRYPTED_LINUX_SEED")
    if not seed:
        seed_file = Path(os.environ.get("ENCRYPTED_LINUX_SEED_FILE", "./seed"))
        if seed_file.is_file():
            seed = seed_file.read_text().strip()

    if not seed:
        # Identity: produces a header byte-identical to stock GCC's
        # behavior. Patched-GCC built with this header is equivalent
        # to unmodified upstream.
        perm = list(range(6))
        seed_hash = "(identity — no seed)"
    else:
        if len(seed.strip()) != 64:
            sys.exit(f"gen-gcc-arg-perm: seed must be 64 hex chars, got {len(seed.strip())}")
        arg_reg_seed = derive_arg_reg_seed(seed)
        perm = fisher_yates(6, arg_reg_seed)
        seed_hash = arg_reg_seed.hex()[:16]

    out = Path(args.output)
    emit_header(perm, seed_hash, out)

    if args.verbose:
        for i, p in enumerate(perm):
            sys.stderr.write(
                f"  arg{i} ({SYSV_ARG_REGS[i]:8}) -> {SYSV_ARG_REGS[p]}\n"
            )
        sys.stderr.write(f"  wrote {out}\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
