#!/usr/bin/env python3
"""
scripts/patch-musl-crt-arch.py — patch musl's _start asm so it passes
argc to _start_c in the PERMUTED register (matching what the scrambling
GCC expects).

musl's arch/x86_64/crt_arch.h has inline asm:
    mov %rsp,%rdi    # canonical: arg0 in RDI

If the seed's arg0 permutation says RDI -> XYZ_REG, we rewrite to:
    mov %rsp,%xyz

Reads the permutation from gcc/config/i386/encrypted-linux-perm.h (the
header generated by gen-gcc-arg-perm.py).

License: Apache-2.0
"""
import os
import re
import sys
from pathlib import Path

# Map GCC register-macro names to the corresponding x86_64 asm register
# (64-bit form, since the asm uses 64-bit ops).
REG_TO_ASM = {
    "DI_REG": "rdi",
    "SI_REG": "rsi",
    "DX_REG": "rdx",
    "CX_REG": "rcx",
    "R8_REG": "r8",
    "R9_REG": "r9",
}

MUSL_SRC = Path(os.environ.get("MUSL_SRC", "/opt/musl"))
PERM_HEADER = Path(os.environ.get(
    "ENCRYPTED_LINUX_PERM",
    "/tmp/encrypted-linux-perm.h"))


def parse_perm_header(p: Path) -> list[str]:
    """Parse encrypted-linux-perm.h and return the 6 registers in
    permuted order (slot 0..5)."""
    src = p.read_text()
    # find the array body
    m = re.search(r'x86_64_int_parameter_registers\[6\][^{]*\{([^}]+)\}', src)
    if not m:
        raise SystemExit(f"can't parse {p}")
    tokens = re.findall(r'[A-Z][A-Z]?[0-9]?_REG', m.group(1))
    if len(tokens) != 6:
        raise SystemExit(f"expected 6 register names, got {len(tokens)}")
    return tokens


def main() -> int:
    if not MUSL_SRC.is_dir():
        sys.exit(f"musl source missing at {MUSL_SRC}")
    if not PERM_HEADER.is_file():
        sys.exit(f"perm header missing at {PERM_HEADER}; "
                 "run scripts/gen-gcc-arg-perm.py first")

    perm_regs = parse_perm_header(PERM_HEADER)
    arg0_reg = REG_TO_ASM[perm_regs[0]]  # slot 0 -> permuted register
    print(f"arg0 (canonical RDI) -> permuted %{arg0_reg}")

    # Patch arch/x86_64/crt_arch.h
    crt = MUSL_SRC / "arch/x86_64/crt_arch.h"
    txt = crt.read_text()

    # Find "mov %rsp,%rdi" and replace %rdi with our arg0 reg.
    new = re.sub(
        r'(\bmov\s+%rsp\s*,\s*)%rdi',
        rf'\g<1>%{arg0_reg}',
        txt
    )
    if new == txt:
        print(f"  WARN: no 'mov %rsp,%rdi' found in {crt}")
    else:
        crt.write_text(new)
        print(f"  patched {crt}: mov %rsp,%rdi -> mov %rsp,%{arg0_reg}")

    # Also patch dynlink crt_arch.h if present (PIE startup).
    dyn = MUSL_SRC / "arch/x86_64/reloc.h"
    if dyn.is_file():
        # Not always needed; some musl versions have it elsewhere. Best-effort.
        pass

    return 0


if __name__ == "__main__":
    sys.exit(main())
